#############################################################################
# Makefile for building: hj_face_project
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 6? 3 09:42:18 2013
# Project:  hj_face_project.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/qmake -o Makefile hj_face_project.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc -lts
CXX           = arm-linux-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtGui -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include/QtSql -I/usr/local/Trolltech/QtEmbedded-4.7.3-arm/include -I/usr/local/arm/include -I. -I.
LINK          = arm-linux-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib -L/usr/local/arm/lib/ -lcv -lhighgui -lcxcore -larm-A8face7552 -lQtSql -L/home/haikong/workdir/Real210/linux-2.6.35-version/source/rootfs_qtopia_qt4/usr/local/tslib/lib -L/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		recognition.cpp \
		avthread.cpp \
		user.cpp \
		adduser.cpp \
		recfailtip.cpp \
		mainmenu.cpp \
		mainkeyboard.cpp \
		login.cpp \
		numkeylogin.cpp \
		home.cpp \
		numkeyboard.cpp \
		informationface.cpp \
		recsuccession.cpp \
		security.cpp \
		administrator.cpp \
		addadminisrator.cpp \
		inputpwd.cpp \
		advancedsetup.cpp \
		baseset.cpp \
		systemtime.cpp \
		networkset.cpp \
		systemset.cpp \
		version.cpp \
		generaluser.cpp \
		finduser.cpp \
		doorpwd.cpp \
		capacity.cpp \
		application.cpp \
		pingb.cpp \
		varmessage.cpp \
		data.cpp \
		dealdata.cpp moc_recognition.cpp \
		moc_avthread.cpp \
		moc_user.cpp \
		moc_adduser.cpp \
		moc_mainkeyboard.cpp \
		moc_recfailtip.cpp \
		moc_mainmenu.cpp \
		moc_login.cpp \
		moc_numkeylogin.cpp \
		moc_home.cpp \
		moc_numkeyboard.cpp \
		moc_informationface.cpp \
		moc_recsuccession.cpp \
		moc_security.cpp \
		moc_administrator.cpp \
		moc_addadminisrator.cpp \
		moc_inputpwd.cpp \
		moc_advancedsetup.cpp \
		moc_baseset.cpp \
		moc_systemtime.cpp \
		moc_networkset.cpp \
		moc_systemset.cpp \
		moc_version.cpp \
		moc_generaluser.cpp \
		moc_finduser.cpp \
		moc_doorpwd.cpp \
		moc_capacity.cpp \
		moc_application.cpp \
		moc_pingb.cpp \
		moc_varmessage.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		recognition.o \
		avthread.o \
		user.o \
		adduser.o \
		recfailtip.o \
		mainmenu.o \
		mainkeyboard.o \
		login.o \
		numkeylogin.o \
		home.o \
		numkeyboard.o \
		informationface.o \
		recsuccession.o \
		security.o \
		administrator.o \
		addadminisrator.o \
		inputpwd.o \
		advancedsetup.o \
		baseset.o \
		systemtime.o \
		networkset.o \
		systemset.o \
		version.o \
		generaluser.o \
		finduser.o \
		doorpwd.o \
		capacity.o \
		application.o \
		pingb.o \
		varmessage.o \
		data.o \
		dealdata.o \
		moc_recognition.o \
		moc_avthread.o \
		moc_user.o \
		moc_adduser.o \
		moc_mainkeyboard.o \
		moc_recfailtip.o \
		moc_mainmenu.o \
		moc_login.o \
		moc_numkeylogin.o \
		moc_home.o \
		moc_numkeyboard.o \
		moc_informationface.o \
		moc_recsuccession.o \
		moc_security.o \
		moc_administrator.o \
		moc_addadminisrator.o \
		moc_inputpwd.o \
		moc_advancedsetup.o \
		moc_baseset.o \
		moc_systemtime.o \
		moc_networkset.o \
		moc_systemset.o \
		moc_version.o \
		moc_generaluser.o \
		moc_finduser.o \
		moc_doorpwd.o \
		moc_capacity.o \
		moc_application.o \
		moc_pingb.o \
		moc_varmessage.o \
		qrc_resource.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/include_source_dir.prf \
		hj_face_project.pro
QMAKE_TARGET  = hj_face_project
DESTDIR       = 
TARGET        = hj_face_project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_recognition.h ui_user.h ui_adduser.h ui_mainkeyboard.h ui_recfailtip.h ui_mainmenu.h ui_login.h ui_numkeylogin.h ui_home.h ui_numkeyboard.h ui_informationface.h ui_recsuccession.h ui_security.h ui_administrator.h ui_addadminisrator.h ui_inputpwd.h ui_advancedsetup.h ui_baseset.h ui_systemtime.h ui_networkset.h ui_systemset.h ui_version.h ui_generaluser.h ui_finduser.h ui_doorpwd.h ui_capacity.h ui_pingb.h ui_varmessage.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hj_face_project.pro  /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtSql.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtCore.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile hj_face_project.pro
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtSql.prl:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtCore.prl:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.7.3-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hj_face_project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hj_face_project1.0.0 || $(MKDIR) .tmp/hj_face_project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hj_face_project1.0.0/ && $(COPY_FILE) --parents recognition.h avthread.h user.h adduser.h mainkeyboard.h common.h recfailtip.h mainmenu.h login.h numkeylogin.h home.h numkeyboard.h informationface.h recsuccession.h security.h administrator.h addadminisrator.h inputpwd.h advancedsetup.h baseset.h systemtime.h networkset.h systemset.h version.h generaluser.h finduser.h doorpwd.h capacity.h application.h pingb.h varmessage.h data.h dealdata.h .tmp/hj_face_project1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/hj_face_project1.0.0/ && $(COPY_FILE) --parents main.cpp recognition.cpp avthread.cpp user.cpp adduser.cpp recfailtip.cpp mainmenu.cpp mainkeyboard.cpp login.cpp numkeylogin.cpp home.cpp numkeyboard.cpp informationface.cpp recsuccession.cpp security.cpp administrator.cpp addadminisrator.cpp inputpwd.cpp advancedsetup.cpp baseset.cpp systemtime.cpp networkset.cpp systemset.cpp version.cpp generaluser.cpp finduser.cpp doorpwd.cpp capacity.cpp application.cpp pingb.cpp varmessage.cpp data.cpp dealdata.cpp .tmp/hj_face_project1.0.0/ && $(COPY_FILE) --parents recognition.ui user.ui adduser.ui mainkeyboard.ui recfailtip.ui mainmenu.ui login.ui numkeylogin.ui home.ui numkeyboard.ui informationface.ui recsuccession.ui security.ui administrator.ui addadminisrator.ui inputpwd.ui advancedsetup.ui baseset.ui systemtime.ui networkset.ui systemset.ui version.ui generaluser.ui finduser.ui doorpwd.ui capacity.ui pingb.ui varmessage.ui .tmp/hj_face_project1.0.0/ && (cd `dirname .tmp/hj_face_project1.0.0` && $(TAR) hj_face_project1.0.0.tar hj_face_project1.0.0 && $(COMPRESS) hj_face_project1.0.0.tar) && $(MOVE) `dirname .tmp/hj_face_project1.0.0`/hj_face_project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hj_face_project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_recognition.cpp moc_avthread.cpp moc_user.cpp moc_adduser.cpp moc_mainkeyboard.cpp moc_recfailtip.cpp moc_mainmenu.cpp moc_login.cpp moc_numkeylogin.cpp moc_home.cpp moc_numkeyboard.cpp moc_informationface.cpp moc_recsuccession.cpp moc_security.cpp moc_administrator.cpp moc_addadminisrator.cpp moc_inputpwd.cpp moc_advancedsetup.cpp moc_baseset.cpp moc_systemtime.cpp moc_networkset.cpp moc_systemset.cpp moc_version.cpp moc_generaluser.cpp moc_finduser.cpp moc_doorpwd.cpp moc_capacity.cpp moc_application.cpp moc_pingb.cpp moc_varmessage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_recognition.cpp moc_avthread.cpp moc_user.cpp moc_adduser.cpp moc_mainkeyboard.cpp moc_recfailtip.cpp moc_mainmenu.cpp moc_login.cpp moc_numkeylogin.cpp moc_home.cpp moc_numkeyboard.cpp moc_informationface.cpp moc_recsuccession.cpp moc_security.cpp moc_administrator.cpp moc_addadminisrator.cpp moc_inputpwd.cpp moc_advancedsetup.cpp moc_baseset.cpp moc_systemtime.cpp moc_networkset.cpp moc_systemset.cpp moc_version.cpp moc_generaluser.cpp moc_finduser.cpp moc_doorpwd.cpp moc_capacity.cpp moc_application.cpp moc_pingb.cpp moc_varmessage.cpp
moc_recognition.cpp: avthread.h \
		common.h \
		recognition.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) recognition.h -o moc_recognition.cpp

moc_avthread.cpp: common.h \
		avthread.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) avthread.h -o moc_avthread.cpp

moc_user.cpp: user.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) user.h -o moc_user.cpp

moc_adduser.cpp: adduser.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) adduser.h -o moc_adduser.cpp

moc_mainkeyboard.cpp: mainkeyboard.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) mainkeyboard.h -o moc_mainkeyboard.cpp

moc_recfailtip.cpp: recfailtip.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) recfailtip.h -o moc_recfailtip.cpp

moc_mainmenu.cpp: mainmenu.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) mainmenu.h -o moc_mainmenu.cpp

moc_login.cpp: login.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_numkeylogin.cpp: recognition.h \
		avthread.h \
		common.h \
		numkeylogin.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) numkeylogin.h -o moc_numkeylogin.cpp

moc_home.cpp: home.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) home.h -o moc_home.cpp

moc_numkeyboard.cpp: numkeyboard.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) numkeyboard.h -o moc_numkeyboard.cpp

moc_informationface.cpp: informationface.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) informationface.h -o moc_informationface.cpp

moc_recsuccession.cpp: recsuccession.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) recsuccession.h -o moc_recsuccession.cpp

moc_security.cpp: security.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) security.h -o moc_security.cpp

moc_administrator.cpp: administrator.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) administrator.h -o moc_administrator.cpp

moc_addadminisrator.cpp: common.h \
		addadminisrator.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) addadminisrator.h -o moc_addadminisrator.cpp

moc_inputpwd.cpp: numkeylogin.h \
		recognition.h \
		avthread.h \
		common.h \
		inputpwd.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) inputpwd.h -o moc_inputpwd.cpp

moc_advancedsetup.cpp: advancedsetup.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) advancedsetup.h -o moc_advancedsetup.cpp

moc_baseset.cpp: baseset.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) baseset.h -o moc_baseset.cpp

moc_systemtime.cpp: systemtime.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) systemtime.h -o moc_systemtime.cpp

moc_networkset.cpp: networkset.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) networkset.h -o moc_networkset.cpp

moc_systemset.cpp: systemset.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) systemset.h -o moc_systemset.cpp

moc_version.cpp: version.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) version.h -o moc_version.cpp

moc_generaluser.cpp: generaluser.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) generaluser.h -o moc_generaluser.cpp

moc_finduser.cpp: finduser.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) finduser.h -o moc_finduser.cpp

moc_doorpwd.cpp: doorpwd.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) doorpwd.h -o moc_doorpwd.cpp

moc_capacity.cpp: capacity.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) capacity.h -o moc_capacity.cpp

moc_application.cpp: pingb.h \
		application.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) application.h -o moc_application.cpp

moc_pingb.cpp: pingb.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) pingb.h -o moc_pingb.cpp

moc_varmessage.cpp: varmessage.h
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/moc $(DEFINES) $(INCPATH) varmessage.h -o moc_varmessage.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		abc.jpg
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_recognition.h ui_user.h ui_adduser.h ui_mainkeyboard.h ui_recfailtip.h ui_mainmenu.h ui_login.h ui_numkeylogin.h ui_home.h ui_numkeyboard.h ui_informationface.h ui_recsuccession.h ui_security.h ui_administrator.h ui_addadminisrator.h ui_inputpwd.h ui_advancedsetup.h ui_baseset.h ui_systemtime.h ui_networkset.h ui_systemset.h ui_version.h ui_generaluser.h ui_finduser.h ui_doorpwd.h ui_capacity.h ui_pingb.h ui_varmessage.h
compiler_uic_clean:
	-$(DEL_FILE) ui_recognition.h ui_user.h ui_adduser.h ui_mainkeyboard.h ui_recfailtip.h ui_mainmenu.h ui_login.h ui_numkeylogin.h ui_home.h ui_numkeyboard.h ui_informationface.h ui_recsuccession.h ui_security.h ui_administrator.h ui_addadminisrator.h ui_inputpwd.h ui_advancedsetup.h ui_baseset.h ui_systemtime.h ui_networkset.h ui_systemset.h ui_version.h ui_generaluser.h ui_finduser.h ui_doorpwd.h ui_capacity.h ui_pingb.h ui_varmessage.h
ui_recognition.h: recognition.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic recognition.ui -o ui_recognition.h

ui_user.h: user.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic user.ui -o ui_user.h

ui_adduser.h: adduser.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic adduser.ui -o ui_adduser.h

ui_mainkeyboard.h: mainkeyboard.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic mainkeyboard.ui -o ui_mainkeyboard.h

ui_recfailtip.h: recfailtip.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic recfailtip.ui -o ui_recfailtip.h

ui_mainmenu.h: mainmenu.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic mainmenu.ui -o ui_mainmenu.h

ui_login.h: login.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic login.ui -o ui_login.h

ui_numkeylogin.h: numkeylogin.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic numkeylogin.ui -o ui_numkeylogin.h

ui_home.h: home.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic home.ui -o ui_home.h

ui_numkeyboard.h: numkeyboard.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic numkeyboard.ui -o ui_numkeyboard.h

ui_informationface.h: informationface.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic informationface.ui -o ui_informationface.h

ui_recsuccession.h: recsuccession.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic recsuccession.ui -o ui_recsuccession.h

ui_security.h: security.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic security.ui -o ui_security.h

ui_administrator.h: administrator.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic administrator.ui -o ui_administrator.h

ui_addadminisrator.h: addadminisrator.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic addadminisrator.ui -o ui_addadminisrator.h

ui_inputpwd.h: inputpwd.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic inputpwd.ui -o ui_inputpwd.h

ui_advancedsetup.h: advancedsetup.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic advancedsetup.ui -o ui_advancedsetup.h

ui_baseset.h: baseset.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic baseset.ui -o ui_baseset.h

ui_systemtime.h: systemtime.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic systemtime.ui -o ui_systemtime.h

ui_networkset.h: networkset.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic networkset.ui -o ui_networkset.h

ui_systemset.h: systemset.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic systemset.ui -o ui_systemset.h

ui_version.h: version.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic version.ui -o ui_version.h

ui_generaluser.h: generaluser.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic generaluser.ui -o ui_generaluser.h

ui_finduser.h: finduser.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic finduser.ui -o ui_finduser.h

ui_doorpwd.h: doorpwd.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic doorpwd.ui -o ui_doorpwd.h

ui_capacity.h: capacity.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic capacity.ui -o ui_capacity.h

ui_pingb.h: pingb.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic pingb.ui -o ui_pingb.h

ui_varmessage.h: varmessage.ui
	/usr/local/Trolltech/QtEmbedded-4.7.3-arm/bin/uic varmessage.ui -o ui_varmessage.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp application.h \
		pingb.h \
		home.h \
		recognition.h \
		avthread.h \
		common.h \
		dealdata.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

recognition.o: recognition.cpp recognition.h \
		avthread.h \
		common.h \
		ui_recognition.h \
		recfailtip.h \
		recsuccession.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recognition.o recognition.cpp

avthread.o: avthread.cpp common.h \
		avthread.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avthread.o avthread.cpp

user.o: user.cpp user.h \
		ui_user.h \
		adduser.h \
		common.h \
		recognition.h \
		avthread.h \
		informationface.h \
		finduser.h \
		data.h \
		dealdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

adduser.o: adduser.cpp adduser.h \
		ui_adduser.h \
		mainkeyboard.h \
		common.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adduser.o adduser.cpp

recfailtip.o: recfailtip.cpp recfailtip.h \
		ui_recfailtip.h \
		recognition.h \
		avthread.h \
		common.h \
		login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recfailtip.o recfailtip.cpp

mainmenu.o: mainmenu.cpp mainmenu.h \
		ui_mainmenu.h \
		user.h \
		security.h \
		advancedsetup.h \
		systemset.h \
		common.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainmenu.o mainmenu.cpp

mainkeyboard.o: mainkeyboard.cpp mainkeyboard.h \
		ui_mainkeyboard.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainkeyboard.o mainkeyboard.cpp

login.o: login.cpp login.h \
		ui_login.h \
		numkeylogin.h \
		recognition.h \
		avthread.h \
		common.h \
		home.h \
		generaluser.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

numkeylogin.o: numkeylogin.cpp numkeylogin.h \
		recognition.h \
		avthread.h \
		common.h \
		ui_numkeylogin.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numkeylogin.o numkeylogin.cpp

home.o: home.cpp home.h \
		ui_home.h \
		numkeyboard.h \
		login.h \
		recognition.h \
		avthread.h \
		common.h \
		application.h \
		pingb.h \
		inputpwd.h \
		numkeylogin.h \
		mainmenu.h \
		generaluser.h \
		data.h \
		dealdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o home.o home.cpp

numkeyboard.o: numkeyboard.cpp numkeyboard.h \
		ui_numkeyboard.h \
		recognition.h \
		avthread.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numkeyboard.o numkeyboard.cpp

informationface.o: informationface.cpp informationface.h \
		ui_informationface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o informationface.o informationface.cpp

recsuccession.o: recsuccession.cpp recsuccession.h \
		ui_recsuccession.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recsuccession.o recsuccession.cpp

security.o: security.cpp security.h \
		ui_security.h \
		administrator.h \
		doorpwd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o security.o security.cpp

administrator.o: administrator.cpp administrator.h \
		ui_administrator.h \
		addadminisrator.h \
		common.h \
		recognition.h \
		avthread.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o administrator.o administrator.cpp

addadminisrator.o: addadminisrator.cpp addadminisrator.h \
		common.h \
		ui_addadminisrator.h \
		mainkeyboard.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addadminisrator.o addadminisrator.cpp

inputpwd.o: inputpwd.cpp inputpwd.h \
		numkeylogin.h \
		recognition.h \
		avthread.h \
		common.h \
		ui_inputpwd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputpwd.o inputpwd.cpp

advancedsetup.o: advancedsetup.cpp advancedsetup.h \
		ui_advancedsetup.h \
		baseset.h \
		systemtime.h \
		networkset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o advancedsetup.o advancedsetup.cpp

baseset.o: baseset.cpp baseset.h \
		ui_baseset.h \
		numkeyboard.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseset.o baseset.cpp

systemtime.o: systemtime.cpp systemtime.h \
		ui_systemtime.h \
		numkeyboard.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemtime.o systemtime.cpp

networkset.o: networkset.cpp networkset.h \
		ui_networkset.h \
		numkeyboard.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networkset.o networkset.cpp

systemset.o: systemset.cpp systemset.h \
		ui_systemset.h \
		version.h \
		capacity.h \
		varmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemset.o systemset.cpp

version.o: version.cpp version.h \
		ui_version.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o version.o version.cpp

generaluser.o: generaluser.cpp generaluser.h \
		ui_generaluser.h \
		user.h \
		data.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generaluser.o generaluser.cpp

finduser.o: finduser.cpp finduser.h \
		ui_finduser.h \
		numkeyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finduser.o finduser.cpp

doorpwd.o: doorpwd.cpp doorpwd.h \
		ui_doorpwd.h \
		numkeyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doorpwd.o doorpwd.cpp

capacity.o: capacity.cpp capacity.h \
		ui_capacity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capacity.o capacity.cpp

application.o: application.cpp application.h \
		pingb.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o application.o application.cpp

pingb.o: pingb.cpp pingb.h \
		ui_pingb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pingb.o pingb.cpp

varmessage.o: varmessage.cpp varmessage.h \
		ui_varmessage.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o varmessage.o varmessage.cpp

data.o: data.cpp data.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

dealdata.o: dealdata.cpp dealdata.h \
		data.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dealdata.o dealdata.cpp

moc_recognition.o: moc_recognition.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recognition.o moc_recognition.cpp

moc_avthread.o: moc_avthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_avthread.o moc_avthread.cpp

moc_user.o: moc_user.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_user.o moc_user.cpp

moc_adduser.o: moc_adduser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adduser.o moc_adduser.cpp

moc_mainkeyboard.o: moc_mainkeyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainkeyboard.o moc_mainkeyboard.cpp

moc_recfailtip.o: moc_recfailtip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recfailtip.o moc_recfailtip.cpp

moc_mainmenu.o: moc_mainmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainmenu.o moc_mainmenu.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_numkeylogin.o: moc_numkeylogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numkeylogin.o moc_numkeylogin.cpp

moc_home.o: moc_home.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_home.o moc_home.cpp

moc_numkeyboard.o: moc_numkeyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numkeyboard.o moc_numkeyboard.cpp

moc_informationface.o: moc_informationface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_informationface.o moc_informationface.cpp

moc_recsuccession.o: moc_recsuccession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recsuccession.o moc_recsuccession.cpp

moc_security.o: moc_security.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_security.o moc_security.cpp

moc_administrator.o: moc_administrator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_administrator.o moc_administrator.cpp

moc_addadminisrator.o: moc_addadminisrator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addadminisrator.o moc_addadminisrator.cpp

moc_inputpwd.o: moc_inputpwd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputpwd.o moc_inputpwd.cpp

moc_advancedsetup.o: moc_advancedsetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_advancedsetup.o moc_advancedsetup.cpp

moc_baseset.o: moc_baseset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_baseset.o moc_baseset.cpp

moc_systemtime.o: moc_systemtime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemtime.o moc_systemtime.cpp

moc_networkset.o: moc_networkset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networkset.o moc_networkset.cpp

moc_systemset.o: moc_systemset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemset.o moc_systemset.cpp

moc_version.o: moc_version.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_version.o moc_version.cpp

moc_generaluser.o: moc_generaluser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_generaluser.o moc_generaluser.cpp

moc_finduser.o: moc_finduser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finduser.o moc_finduser.cpp

moc_doorpwd.o: moc_doorpwd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_doorpwd.o moc_doorpwd.cpp

moc_capacity.o: moc_capacity.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_capacity.o moc_capacity.cpp

moc_application.o: moc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_application.o moc_application.cpp

moc_pingb.o: moc_pingb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pingb.o moc_pingb.cpp

moc_varmessage.o: moc_varmessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_varmessage.o moc_varmessage.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

